name: jimu_app
description: Descrição.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Meus packages:
  alimentos:
    path: packages/alimentos
  
  compartilhado:
    path: packages/compartilhado
    
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
